version: "3.1"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: spots
      POSTGRES_PASSWORD: spots
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
